# Change these first
owner: uccnetsoc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: netsoc.co
    url: https://netsoc.co
  - name: netsoc.cloud
    url: https://netsoc.cloud
  - name: wiki.netsoc.co
    url: https://wiki.netsoc.co
  - name: blog.netsoc.co
    url: https://blog.netsoc.co
  - name: Netsoc Cloud API
    url: https://api.netsoc.cloud/docs
  - name: Netsoc Cloud UI
    url: https://netsoc.cloud
  - name: Netsoc Cloud Authentication Services
    url: https://keycloak.netsoc.co
  - name: Netsoc Cloud LXC Services
    url: https://whoami-lxc-thomas-container.netsoc.cloud
  - name: Netsoc Cloud VPS Services
    url: https://whoami-vps-thomas-vps.netsoc.cloud

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.netsoc.co
  # for some reason not being bundled into gh-pages branch and won't work with raw github url
  themeUrl: https://cdn.statically.io/gh/uccnetsoc/upptime/master/assets/netsoc.css
  name: Status
  introTitle: "Netsoc status page"
  introMessage: Netsoc Status page, using [upptime](https://github.com/upptime/upptime), which is run on GitHub Actions to generate uptime statistics and ping graphs. **Note** response times are inflated due to running on GitHub runners, and not a more natural environment.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
